In [1]:
#the purpose of this notebook is to split ../../gen_data/train2.csv into training set(s), targets , 
#validation set(s), validation targets.

#inputs: ../../gen_data/train2.csv
#outputs:
            #python list of training set(s)
            #python list of targets
            #python list of validation set(s) identical in format to ../../original_data/test.csv.gz

In [2]:
import numpy as np
import pandas as pd
import pickle

In [3]:
train2 = pd.read_csv('../../gen_data/train2.csv')
train2.head()

,date_block_num,shop_id,item_id,item_category_id,shop_name,item_name,item_category_name,item_cnt_month
0,0,2,27,19,"Адыгея ТЦ ""Мега""","007 Legends [PS3, русская версия]",Игры - PS3,1.0
1,0,2,33,37,"Адыгея ТЦ ""Мега""",1+1 (BD),Кино - Blu-Ray,1.0
2,0,2,317,45,"Адыгея ТЦ ""Мега""",1С:Аудиокниги. Мединский В. Мифы о России. О р...,Книги - Аудиокниги 1С,1.0
3,0,2,438,45,"Адыгея ТЦ ""Мега""",1С:Аудиотеатр. Лучшие произведения русских пис...,Книги - Аудиокниги 1С,1.0
4,0,2,471,49,"Адыгея ТЦ ""Мега""",1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,Книги - Методические материалы 1С,2.0

In [4]:
#as a reference, get test
test = pd.read_csv('../../original_data/test.csv.gz')
test.head()

   ID  shop_id  item_id
0   0        5     5037
1   1        5     5320
2   2        5     5233
3   3        5     5232
4   4        5     5268

In [5]:
np.mean(train2.date_block_num.isna())

0.0

In [6]:
training_bool = train2['date_block_num']<32.5
y_train_to_32 = train2['item_cnt_month'][training_bool]
x_train_to_32 = train2.drop('item_cnt_month',axis=1)[training_bool]

In [7]:
validation_bool = train2['date_block_num']>32.5
validation_33 = train2[validation_bool].merge(test,'right',on=['item_id','shop_id'])

In [8]:
validation_33.shape

(214200, 9)

In [9]:
validation_33.tail()

,date_block_num,shop_id,item_id,item_category_id,shop_name,item_name,item_category_name,item_cnt_month,ID
214195,NaN,45,18027,NaN,NaN,NaN,NaN,NaN,214194
214196,NaN,45,16188,NaN,NaN,NaN,NaN,NaN,214196
214197,NaN,45,15757,NaN,NaN,NaN,NaN,NaN,214197
214198,NaN,45,19648,NaN,NaN,NaN,NaN,NaN,214198
214199,NaN,45,969,NaN,NaN,NaN,NaN,NaN,214199

In [10]:
#dropped this, x_valid_33 is the same as test, only need y_valid_33

#need to drop columns to make it like test.csv in original_data
#validation_33.drop(['date_block_num','item_category_id','shop_name','item_name','item_category_name'],axis=1,inplace=True)
#validation_33.head()

In [11]:
validation_33['item_cnt_month'].fillna(0,inplace=True)

In [12]:
validation_33

,date_block_num,shop_id,item_id,item_category_id,shop_name,item_name,item_category_name,item_cnt_month,ID
0,33.0,2,31,37.0,"Адыгея ТЦ ""Мега""",007: КООРДИНАТЫ «СКАЙФОЛЛ» (BD),Кино - Blu-Ray,1.0,20994
1,33.0,2,486,73.0,"Адыгея ТЦ ""Мега""",1С:Бухгалтерия 8. Учебная версия. Издание 8.,Программы - 1С:Предприятие 8,3.0,21001
2,33.0,2,787,49.0,"Адыгея ТЦ ""Мега""",1С:Предпр.8. Управление торг.операциями в вопр...,Книги - Методические материалы 1С,1.0,20986
3,33.0,2,794,73.0,"Адыгея ТЦ ""Мега""",1С:Предприниматель 2015,Программы - 1С:Предприятие 8,1.0,22120
4,33.0,2,968,40.0,"Адыгея ТЦ ""Мега""",3 ДНЯ НА УБИЙСТВО,Кино - DVD,1.0,22459
5,33.0,2,988,37.0,"Адыгея ТЦ ""Мега""",38-Я ПАРАЛЛЕЛЬ (BD),Кино - Blu-Ray,1.0,21736
6,33.0,2,1075,40.0,"Адыгея ТЦ ""Мега""",47 РОНИНОВ,Кино - DVD,1.0,23486
7,33.0,2,1121,55.0,"Адыгея ТЦ ""Мега""",A-HA Cast In Steel,Музыка - CD локального производства,1.0,20972
8,33.0,2,1377,23.0,"Адыгея ТЦ ""Мега""",Alan Wake [Xbox 360],Игры - XBOX 360,1.0,21682
9,33.0,2,1387,28.0,"Адыгея ТЦ ""Мега""","Alien: Isolation. Nostromo Edition [PC, русска...",Игры PC - Дополнительные издания,1.0,21683
10,33.0,2,1389,20.0,"Адыгея ТЦ ""Мега""","Alien: Isolation. Nostromo Edition [PS4, русск...",Игры - PS4,1.0,21734
11,33.0,2,1466,23.0,"Адыгея ТЦ ""Мега""",Assassin's Creed 2 Game of the Year Edition (C...,Игры - XBOX 360,2.0,20917
12,33.0,2,1486,23.0,"Адыгея ТЦ ""Мега""",Assassin's Creed IV. Черный флаг (Classics) [X...,Игры - XBOX 360,1.0,20920
13,33.0,2,1523,21.0,"Адыгея ТЦ ""Мега""",Assassin's Creed. Bloodlines (Essentials) [PSP...,Игры - PSP,1.0,22428
14,33.0,2,1534,28.0,"Адыгея ТЦ ""Мега""","Assassin's Creed. Сага о Новом Свете [PC, русс...",Игры PC - Дополнительные издания,1.0,20901
15,33.0,2,1535,23.0,"Адыгея ТЦ ""Мега""",Assassin's Creed. Сага о Новом Свете [Xbox 360...,Игры - XBOX 360,1.0,20902
16,33.0,2,1540,20.0,"Адыгея ТЦ ""Мега""","Assassin's Creed: Единство [PS4, русская версия]",Игры - PS4,2.0,20923
17,33.0,2,1556,20.0,"Адыгея ТЦ ""Мега""",Assassin's Creed: Единство. Специальное издани...,Игры - PS4,1.0,22467
18,33.0,2,1560,23.0,"Адыгея ТЦ ""Мега""","Assassin's Creed: Изгой (Classics) [Xbox 360, ...",Игры - XBOX 360,1.0,21305
19,33.0,2,1563,30.0,"Адыгея ТЦ ""Мега""","Assassin's Creed: Изгой [PC, русская версия]",Игры PC - Стандартные издания,1.0,20925
20,33.0,2,1569,19.0,"Адыгея ТЦ ""Мега""",Assassin's Creed: Изгой. Коллекционное издание...,Игры - PS3,1.0,20909
21,33.0,2,1571,23.0,"Адыгея ТЦ ""Мега""",Assassin's Creed: Откровения (Classics) [Xbox ...,Игры - XBOX 360,1.0,21307
22,33.0,2,1578,20.0,"Адыгея ТЦ ""Мега""","Assassin's Creed: Синдикат. Биг Бен [PS4, русс...",Игры - PS4,4.0,21022
23,33.0,2,1579,24.0,"Адыгея ТЦ ""Мега""","Assassin's Creed: Синдикат. Биг Бен [Xbox One,...",Игры - XBOX ONE,1.0,22465
24,33.0,2,1583,20.0,"Адыгея ТЦ ""Мега""",Assassin's Creed: Синдикат. Специальное издани...,Игры - PS4,9.0,20898
25,33.0,2,1586,20.0,"Адыгея ТЦ ""Мега""","Assassin's Creed: Синдикат. Чаринг-Кросс [PS4,...",Игры - PS4,1.0,22136
26,33.0,2,1813,30.0,"Адыгея ТЦ ""Мега""","Batman: Рыцарь Аркхема [PC, Jewel, русские суб...",Игры PC - Стандартные издания,1.0,23122
27,33.0,2,1847,19.0,"Адыгея ТЦ ""Мега""","Battlefield 4 (Essentials) [PS3, русская версия]",Игры - PS3,2.0,20905
28,33.0,2,1857,20.0,"Адыгея ТЦ ""Мега""","Battlefield 4 [PS4, русская версия]",Игры - PS4,1.0,22426
29,33.0,2,1876,19.0,"Адыгея ТЦ ""Мега""","Battlefield Hardline [PS3, русская версия]",Игры - PS3,1.0,20906
...,...,...,...,...,...,...,...,...,...
214170,NaN,45,12491,NaN,NaN,NaN,NaN,0.0,214168
214171,NaN,45,13515,NaN,NaN,NaN,NaN,0.0,214169
214172,NaN,45,14543,NaN,NaN,NaN,NaN,0.0,214170
214173,NaN,45,19253,NaN,NaN,NaN,NaN,0.0,214171
214174,NaN,45,17957,NaN,NaN,NaN,NaN,0.0,214172
214175,NaN,45,12470,NaN,NaN,NaN,NaN,0.0,214173
214176,NaN,45,7543,NaN,NaN,NaN,NaN,0.0,214174
214177,NaN,45,6661,NaN,NaN,NaN,NaN,0.0,214175
214178,NaN,45,11137,NaN,NaN,NaN,NaN,0.0,214176
214179,NaN,45,11489,NaN,NaN,NaN,NaN,0.0,214177
214180,NaN,45,9782,NaN,NaN,NaN,NaN,0.0,214178
214181,NaN,45,2972,NaN,NaN,NaN,NaN,0.0,214179
214182,NaN,45,19889,NaN,NaN,NaN,NaN,0.0,214180
214183,NaN,45,20650,NaN,NaN,NaN,NaN,0.0,214181
214184,NaN,45,5665,NaN,NaN,NaN,NaN,0.0,214182
214185,NaN,45,9978,NaN,NaN,NaN,NaN,0.0,214183
214186,NaN,45,10767,NaN,NaN,NaN,NaN,0.0,214184
214187,NaN,45,14443,NaN,NaN,NaN,NaN,0.0,214185
214188,NaN,45,14341,NaN,NaN,NaN,NaN,0.0,214186
214189,NaN,45,9500,NaN,NaN,NaN,NaN,0.0,214188
214190,NaN,45,16007,NaN,NaN,NaN,NaN,0.0,214189
214191,NaN,45,3280,NaN,NaN,NaN,NaN,0.0,214190
214192,NaN,45,4393,NaN,NaN,NaN,NaN,0.0,214191
214193,NaN,45,4352,NaN,NaN,NaN,NaN,0.0,214192
214194,NaN,45,18049,NaN,NaN,NaN,NaN,0.0,214193
214195,NaN,45,18027,NaN,NaN,NaN,NaN,0.0,214194
214196,NaN,45,16188,NaN,NaN,NaN,NaN,0.0,214196
214197,NaN,45,15757,NaN,NaN,NaN,NaN,0.0,214197
214198,NaN,45,19648,NaN,NaN,NaN,NaN,0.0,214198
214199,NaN,45,969,NaN,NaN,NaN,NaN,0.0,214199

In [13]:
#dropped this, x_valid_33 is the same as test, only need y_valid_33

#x_valid_33 = validation_33[['ID','shop_id','item_id']]
y_valid_33 = validation_33['item_cnt_month']
#x_valid_33.head()

In [14]:
#now prep train test data
y_train_to_33 = train2['item_cnt_month']
x_train_to_33 = train2.drop('item_cnt_month',axis=1)

In [15]:
#dropped this, x_valid_33 is the same as test, only need y_valid_33

#x_valid_33 = x_valid_33.sort_values('ID')

In [16]:
y_test_nans = pd.Series(np.full(test.shape[0],np.nan))

In [17]:
np.mean(validation_33.date_block_num.isna())

0.8674042950513539

In [18]:
validation_33.shape

(214200, 9)

# save

In [19]:
#save items as a list so that I can add more validation schemes later
pickle.dump([x_train_to_32,x_train_to_33],open('../../gen_data/x_train--simple_validation_split.ipynb--.pickle','wb'))
pickle.dump([y_train_to_32,y_train_to_33],open('../../gen_data/y_train--simple_validation_split.ipynb--.pickle','wb'))
pickle.dump([test,test],open('../../gen_data/x_val--simple_validation_split.ipynb--.pickle','wb'))
pickle.dump([y_valid_33,y_test_nans],open('../../gen_data/y_val--simple_validation_split.ipynb--.pickle','wb'))

In [20]:
#with pd.option_context('display.max_rows',None,'display.max_columns',None):
#    print(y_valid_33)

In [21]:
y_valid_33.shape

(214200,)

In [22]:
train2[train2.date_block_num>32.5].shape

(31531, 8)

In [23]:
y_valid_33[~y_valid_33.isna()].shape

(214200,)

In [24]:
y_train_to_33.shape

(1609124,)

In [25]:
x_train_to_33.shape

(1609124, 7)

# check

In [26]:
train2_33 = train2[train2.date_block_num==33][['shop_id','item_id','item_cnt_month']]
train2_33.columns = ['shop_id','item_id','original_target']
train2_33.head()

         shop_id  item_id  original_target
1577593        2       31              1.0
1577594        2      486              3.0
1577595        2      787              1.0
1577596        2      794              1.0
1577597        2      968              1.0

In [27]:
validation_33.head()

,date_block_num,shop_id,item_id,item_category_id,shop_name,item_name,item_category_name,item_cnt_month,ID
0,33.0,2,31,37.0,"Адыгея ТЦ ""Мега""",007: КООРДИНАТЫ «СКАЙФОЛЛ» (BD),Кино - Blu-Ray,1.0,20994
1,33.0,2,486,73.0,"Адыгея ТЦ ""Мега""",1С:Бухгалтерия 8. Учебная версия. Издание 8.,Программы - 1С:Предприятие 8,3.0,21001
2,33.0,2,787,49.0,"Адыгея ТЦ ""Мега""",1С:Предпр.8. Управление торг.операциями в вопр...,Книги - Методические материалы 1С,1.0,20986
3,33.0,2,794,73.0,"Адыгея ТЦ ""Мега""",1С:Предприниматель 2015,Программы - 1С:Предприятие 8,1.0,22120
4,33.0,2,968,40.0,"Адыгея ТЦ ""Мега""",3 ДНЯ НА УБИЙСТВО,Кино - DVD,1.0,22459

In [28]:
all(validation_33.item_cnt_month == y_valid_33)

True

In [29]:
validation_33.shape

(214200, 9)

In [30]:
merged = validation_33.merge(train2_33,how='left',on=['shop_id','item_id'])

In [31]:
all(merged[~merged.original_target.isna()]['item_cnt_month'] == merged[~merged.original_target.isna()]['original_target'])

True

In [32]:
np.mean(y_valid_33==0)

0.8676190476190476

In [33]:
train2[train2.date_block_num==33].shape

(31531, 8)