In [1]:
import pandas as pd
import numpy as np 
import pickle
import xgboost as xgb
import time
import graphviz
import matplotlib as plt

In [2]:
START_NOTEBOOK = time.time()
SUB=False

In [3]:
pik = pickle.load(open('../saved_datasets/19-3-19,pipeline_A_reduced,dateback=12/xtrain_xtest_ytrain_ytest.pickle','rb'))
#x_train , x_test , y_train , y_test = [[x[0]] for x in pik]

In [4]:
x_train , x_test , y_train , y_test = pik

In [5]:
x_train[0].shape
y_train[0].shape

(9934775,)

In [6]:
x_train[0].head()

,date_block_num,shop_id,item_id,item_category_id,first_sale_date_block,new_item,city,item_type,item_info,prop_median_item_price,...,sum_city_item_back_2,sum_city_item_cat_back_2,sum_itemtype_shop_back_2,sum_itemtype_city_back_2,month,numdays,mean_prevmonth_item_price,std_prevmonth_item_price,median_prevmonth_item_price,median_prevmonth_shop_item_price
0,2,2,30,40,1.0,0.0,Адыгея,Кино,DVD,NaN,...,0.0,0.0,0.0,0.0,mar,31,383.921877,40.382137,399.0,NaN
1,2,2,31,37,1.0,0.0,Адыгея,Кино,Blu-Ray,1.0,...,0.0,0.0,0.0,0.0,mar,31,666.991044,71.236204,699.0,699.0
2,2,2,482,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,1.0,...,1.0,7.0,88.0,88.0,mar,31,3280.224138,73.482784,3300.0,3300.0
3,2,2,484,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,1.0,...,2.0,7.0,88.0,88.0,mar,31,299.175610,6.709385,300.0,300.0
4,2,2,687,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,NaN,...,0.0,0.0,0.0,0.0,mar,31,600.000000,0.000000,600.0,NaN

# Preprocessing

In [7]:
#save x_train[1] to create submission later (becuase i delete shop and item ids)
x_test_1_saved = x_test[1][['shop_id','item_id']]

In [8]:
x_train[0]

,date_block_num,shop_id,item_id,item_category_id,first_sale_date_block,new_item,city,item_type,item_info,prop_median_item_price,...,sum_city_item_back_2,sum_city_item_cat_back_2,sum_itemtype_shop_back_2,sum_itemtype_city_back_2,month,numdays,mean_prevmonth_item_price,std_prevmonth_item_price,median_prevmonth_item_price,median_prevmonth_shop_item_price
0,2,2,30,40,1.0,0.0,Адыгея,Кино,DVD,NaN,...,0.0,0.0,0.0,0.0,mar,31,383.921877,40.382137,399.00,NaN
1,2,2,31,37,1.0,0.0,Адыгея,Кино,Blu-Ray,1.00000,...,0.0,0.0,0.0,0.0,mar,31,666.991044,71.236204,699.00,699.0
2,2,2,482,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,1.00000,...,1.0,7.0,88.0,88.0,mar,31,3280.224138,73.482784,3300.00,3300.0
3,2,2,484,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,1.00000,...,2.0,7.0,88.0,88.0,mar,31,299.175610,6.709385,300.00,300.0
4,2,2,687,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,NaN,...,0.0,0.0,0.0,0.0,mar,31,600.000000,0.000000,600.00,NaN
5,2,2,785,49,0.0,0.0,Адыгея,Книги,Методические материалы 1С,1.00000,...,1.0,8.0,27.0,27.0,mar,31,349.000000,0.000000,349.00,349.0
6,2,2,791,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,1.00000,...,2.0,7.0,88.0,88.0,mar,31,600.000000,0.000000,600.00,600.0
7,2,2,835,73,0.0,0.0,Адыгея,Программы,1С:Предприятие 8,1.00000,...,0.0,0.0,0.0,0.0,mar,31,4600.000000,0.000000,4600.00,4600.0
8,2,2,1007,67,0.0,0.0,Адыгея,Подарки,Развитие,1.00000,...,3.0,28.0,102.0,102.0,mar,31,439.846094,39.614302,449.00,449.0
9,2,2,1013,67,0.0,0.0,Адыгея,Подарки,Развитие,NaN,...,3.0,28.0,102.0,102.0,mar,31,299.000000,0.000000,299.00,NaN
10,2,2,1023,67,0.0,0.0,Адыгея,Подарки,Развитие,NaN,...,2.0,28.0,102.0,102.0,mar,31,299.000000,0.000000,299.00,NaN
11,2,2,1025,67,0.0,0.0,Адыгея,Подарки,Развитие,NaN,...,0.0,0.0,0.0,0.0,mar,31,498.972727,0.127920,499.00,NaN
12,2,2,1398,30,1.0,0.0,Адыгея,Игры PC,Стандартные издания,1.00000,...,0.0,0.0,0.0,0.0,mar,31,572.503207,67.977212,599.00,599.0
13,2,2,1407,19,1.0,0.0,Адыгея,Игры,PS3,0.79992,...,0.0,0.0,0.0,0.0,mar,31,2308.583333,243.520937,2499.00,1999.0
14,2,2,1418,30,0.0,0.0,Адыгея,Игры PC,Стандартные издания,NaN,...,3.0,223.0,263.0,263.0,mar,31,348.997222,0.026352,349.00,NaN
15,2,2,1420,30,0.0,0.0,Адыгея,Игры PC,Стандартные издания,1.00000,...,3.0,223.0,263.0,263.0,mar,31,348.828571,1.756620,349.00,349.0
16,2,2,1459,19,2.0,1.0,Адыгея,Игры,PS3,NaN,...,0.0,0.0,0.0,0.0,mar,31,NaN,NaN,NaN,NaN
17,2,2,1461,19,2.0,1.0,Адыгея,Игры,PS3,NaN,...,0.0,0.0,0.0,0.0,mar,31,NaN,NaN,NaN,NaN
18,2,2,1462,23,2.0,1.0,Адыгея,Игры,XBOX 360,NaN,...,0.0,0.0,0.0,0.0,mar,31,NaN,NaN,NaN,NaN
19,2,2,1470,30,0.0,0.0,Адыгея,Игры PC,Стандартные издания,NaN,...,4.0,223.0,263.0,263.0,mar,31,674.259519,43.121207,699.00,NaN
20,2,2,1472,23,0.0,0.0,Адыгея,Игры,XBOX 360,NaN,...,3.0,35.0,240.0,240.0,mar,31,2554.040000,139.214595,2599.00,NaN
21,2,2,1481,22,0.0,0.0,Адыгея,Игры,PSVita,NaN,...,1.0,32.0,240.0,240.0,mar,31,1963.593137,107.875013,1999.00,NaN
22,2,2,1523,21,0.0,0.0,Адыгея,Игры,PSP,NaN,...,6.0,50.0,240.0,240.0,mar,31,798.627869,3.619461,799.00,NaN
23,2,2,1602,62,0.0,0.0,Адыгея,Подарки,"Гаджеты, роботы, спорт",NaN,...,0.0,0.0,0.0,0.0,mar,31,298.000000,NaN,298.00,NaN
24,2,2,1800,30,0.0,0.0,Адыгея,Игры PC,Стандартные издания,NaN,...,0.0,0.0,0.0,0.0,mar,31,321.445055,99.560735,274.50,NaN
25,2,2,1830,30,0.0,0.0,Адыгея,Игры PC,Стандартные издания,NaN,...,0.0,0.0,0.0,0.0,mar,31,486.933626,138.804903,599.00,NaN
26,2,2,1832,19,0.0,0.0,Адыгея,Игры,PS3,NaN,...,1.0,114.0,240.0,240.0,mar,31,1244.023279,395.924459,999.50,NaN
27,2,2,1835,28,0.0,0.0,Адыгея,Игры PC,Дополнительные издания,NaN,...,2.0,37.0,263.0,263.0,mar,31,1951.761364,130.315493,1999.00,NaN
28,2,2,1871,30,0.0,0.0,Адыгея,Игры PC,Стандартные издания,1.00000,...,1.0,223.0,263.0,263.0,mar,31,299.000000,0.000000,299.00,299.0
29,2,2,1889,21,0.0,0.0,Адыгея,Игры,PSP,NaN,...,1.0,50.0,240.0,240.0,mar,31,582.355952,41.053882,599.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9934745,32,59,14430,40,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,162.333333,11.547005,169.00,NaN
9934746,32,59,15971,61,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,249.000000,0.000000,249.00,NaN
9934747,32,59,16055,64,17.0,0.0,Ярославль,Подарки,Настольные игры,1.00000,...,1.0,10.0,240.0,240.0,sep,30,599.000000,0.000000,599.00,599.0
9934748,32,59,16084,65,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,449.000000,0.000000,449.00,NaN
9934749,32,59,16179,64,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,2071.222222,242.527204,1949.00,NaN
9934750,32,59,16243,64,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,2499.000000,0.000000,2499.00,NaN
9934751,32,59,16540,55,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,198.000000,0.000000,198.00,NaN
9934752,32,59,18715,40,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,199.000000,0.000000,199.00,NaN
9934753,32,59,19501,61,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,799.000000,NaN,799.00,NaN
9934754,32,59,19745,37,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,299.000000,0.000000,299.00,NaN
9934755,32,59,19789,41,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,199.000000,NaN,199.00,NaN
9934756,32,59,19885,55,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,299.000000,NaN,299.00,NaN
9934757,32,59,20070,40,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,399.000000,NaN,399.00,NaN
9934758,32,59,6400,23,24.0,0.0,Ярославль,Игры,XBOX 360,1.00000,...,0.0,0.0,0.0,0.0,sep,30,999.000000,0.000000,999.00,999.0
9934759,32,59,9150,37,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934760,32,59,9496,40,27.0,0.0,Ярославль,Кино,DVD,NaN,...,0.0,0.0,0.0,0.0,sep,30,99.000000,0.000000,99.00,NaN
9934761,32,59,9949,40,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,198.310000,71.686485,198.31,NaN
9934762,32,59,13379,49,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934763,32,59,13521,23,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934764,32,59,15443,63,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934765,32,59,16729,40,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,79.000000,NaN,79.00,NaN
9934766,32,59,18024,70,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,299.000000,0.000000,299.00,NaN
9934767,32,59,20267,40,0.0,0.0,0,0,0,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934768,32,59,4608,58,1.0,0.0,Ярославль,Музыка,Винил,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934769,32,59,4779,30,0.0,0.0,Ярославль,Игры PC,Стандартные издания,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934770,32,59,10656,67,29.0,0.0,Ярославль,Подарки,Развитие,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934771,32,59,14899,37,0.0,0.0,Ярославль,Кино,Blu-Ray,NaN,...,0.0,0.0,0.0,0.0,sep,30,349.000000,0.000000,349.00,NaN
9934772,32,59,18577,37,4.0,0.0,Ярославль,Кино,Blu-Ray,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934773,32,59,21459,37,3.0,0.0,Ярославль,Кино,Blu-Ray,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN
9934774,32,59,22043,37,6.0,0.0,Ярославль,Кино,Blu-Ray,NaN,...,0.0,0.0,0.0,0.0,sep,30,NaN,NaN,NaN,NaN

In [9]:
def preproc_model3(x_train,x_test,y_train,y_test):
    x_train = [d.drop(['date_block_num','shop_id','item_id','item_category_id','month'],axis=1) for d in x_train]
    x_test =  [d.drop(['date_block_num','shop_id','item_id','item_category_id','month'],axis=1) for d in x_test]
    y_train = [d.clip(0,20) for d in y_train]
    y_test =  [d.clip(0,20) for d in y_test]
    return [x_train,x_test,y_train,y_test]

In [10]:
x_train , x_test , y_train , y_test = preproc_model3(x_train,x_test,y_train,y_test)

In [11]:
a = x_test[0].columns.tolist()
b = x_train[0].columns.tolist()
a==b

False

# HACKS

### sort columns

In [12]:
x_train[0].columns.tolist()

['first_sale_date_block',
 'new_item',
 'city',
 'item_type',
 'item_info',
 'prop_median_item_price',
 'sum_item_sales_back_1',
 'sum_shop_sales_back_1',
 'item_cnt_month_back_1',
 'sum_item_cat_sales_back_1',
 'sum_item_cat_shop_sales_back_1',
 'sum_city_back_1',
 'sum_itemtype_back_1',
 'sum_iteminfo_back_1',
 'sum_city_item_back_1',
 'sum_city_item_cat_back_1',
 'sum_itemtype_shop_back_1',
 'sum_itemtype_city_back_1',
 'sum_item_sales_back_2',
 'sum_shop_sales_back_2',
 'item_cnt_month_back_2',
 'sum_item_cat_sales_back_2',
 'sum_item_cat_shop_sales_back_2',
 'sum_city_back_2',
 'sum_itemtype_back_2',
 'sum_iteminfo_back_2',
 'sum_city_item_back_2',
 'sum_city_item_cat_back_2',
 'sum_itemtype_shop_back_2',
 'sum_itemtype_city_back_2',
 'numdays',
 'mean_prevmonth_item_price',
 'std_prevmonth_item_price',
 'median_prevmonth_item_price',
 'median_prevmonth_shop_item_price']

In [13]:
x_test[0].columns.tolist()

['first_sale_date_block',
 'new_item',
 'city',
 'item_type',
 'item_info',
 'prop_median_item_price',
 'sum_item_sales_back_1',
 'sum_shop_sales_back_1',
 'item_cnt_month_back_1',
 'sum_item_cat_sales_back_1',
 'sum_item_cat_shop_sales_back_1',
 'sum_city_back_1',
 'sum_itemtype_back_1',
 'sum_iteminfo_back_1',
 'sum_city_item_back_1',
 'sum_city_item_cat_back_1',
 'sum_itemtype_shop_back_1',
 'sum_itemtype_city_back_1',
 'sum_item_sales_back_2',
 'sum_shop_sales_back_2',
 'item_cnt_month_back_2',
 'sum_item_cat_sales_back_2',
 'sum_item_cat_shop_sales_back_2',
 'sum_city_back_2',
 'sum_itemtype_back_2',
 'sum_iteminfo_back_2',
 'sum_city_item_back_2',
 'sum_city_item_cat_back_2',
 'sum_itemtype_shop_back_2',
 'sum_itemtype_city_back_2',
 'numdays',
 'mean_prevmonth_item_price',
 'std_prevmonth_item_price',
 'median_prevmonth_item_price',
 'median_prevmonth_shop_item_price',
 'target']

In [14]:
train_cols = x_train[0].columns.tolist()
x_test[0] = x_test[0][train_cols]

In [15]:
A = x_train[0].columns.tolist()

In [16]:
B = x_test[0].columns.tolist()

In [17]:
A==B

True

### fillnas in y_test

In [18]:
#y_test = [d.fillna(0) for d in y_test]

## TODO: account for factor adjustment

# Eval Metric

In [19]:
np.array([1,2,3]).clip(0,1)

array([1, 1, 1])

In [20]:
def model3_eval(preds,true_y):
    preds_clipped = preds.clip(0,20)
    true_y_clipped = true_y.clip(0,20)
    sq_res = (preds_clipped - true_y_clipped)**2
    return  np.sqrt(np.mean(sq_res))

# Objective metric

In [21]:
#def model3_objective(preds,true_y):

In [22]:
np.mean(y_test[0].isna())

0.0

# Notes

- There are likely too many feats, this would explain immediate overfitting
- rmse withou clipped data is gonna put a lot of focus on large outliers
* consider mean abs error

# Feature Selection

In [23]:
x_train[0].columns.tolist()

['first_sale_date_block',
 'new_item',
 'city',
 'item_type',
 'item_info',
 'prop_median_item_price',
 'sum_item_sales_back_1',
 'sum_shop_sales_back_1',
 'item_cnt_month_back_1',
 'sum_item_cat_sales_back_1',
 'sum_item_cat_shop_sales_back_1',
 'sum_city_back_1',
 'sum_itemtype_back_1',
 'sum_iteminfo_back_1',
 'sum_city_item_back_1',
 'sum_city_item_cat_back_1',
 'sum_itemtype_shop_back_1',
 'sum_itemtype_city_back_1',
 'sum_item_sales_back_2',
 'sum_shop_sales_back_2',
 'item_cnt_month_back_2',
 'sum_item_cat_sales_back_2',
 'sum_item_cat_shop_sales_back_2',
 'sum_city_back_2',
 'sum_itemtype_back_2',
 'sum_iteminfo_back_2',
 'sum_city_item_back_2',
 'sum_city_item_cat_back_2',
 'sum_itemtype_shop_back_2',
 'sum_itemtype_city_back_2',
 'numdays',
 'mean_prevmonth_item_price',
 'std_prevmonth_item_price',
 'median_prevmonth_item_price',
 'median_prevmonth_shop_item_price']

In [27]:
def feat_selection(x_train,x_test,y_train,y_test):
    FEATS=[
# 'first_sale_date_block',
# 'new_item',
# 'prop_median_item_price',
 'sum_item_sales_back_1',
 'sum_shop_sales_back_1',
 'item_cnt_month_back_1',
 'sum_item_cat_sales_back_1',
 'sum_item_cat_shop_sales_back_1',
 'sum_city_back_1',
 'sum_itemtype_back_1',
 'sum_iteminfo_back_1',
 'sum_city_item_back_1',
 'sum_city_item_cat_back_1',
 'sum_itemtype_shop_back_1',
 'sum_itemtype_city_back_1',
 'sum_item_sales_back_2',
 'sum_shop_sales_back_2',
 'item_cnt_month_back_2',
 'sum_item_cat_sales_back_2',
 'sum_item_cat_shop_sales_back_2',
 'sum_city_back_2',
 'sum_itemtype_back_2',
 'sum_iteminfo_back_2',
 'sum_city_item_back_2',
 'sum_city_item_cat_back_2',
 'sum_itemtype_shop_back_2',
 'sum_itemtype_city_back_2']#,
# 'numdays',
# 'mean_prevmonth_item_price',
# 'std_prevmonth_item_price',
# 'median_prevmonth_item_price',
# 'median_prevmonth_shop_item_price']
    x_train = [d[FEATS] for d in x_train]
    x_test =  [d[FEATS] for d in x_test]
    return [x_train,x_test,y_train,y_test]

def feat_selection(x_train,x_test,y_train,y_test):
    FEATS= [
 'sum_item_sales_back_1',
 'sum_shop_sales_back_1',
 'item_cnt_month_back_1',
 'sum_item_cat_sales_back_1',
 'sum_item_cat_shop_sales_back_1',
 'sum_item_sales_back_2',
 'sum_shop_sales_back_2',
 'item_cnt_month_back_2',
 'sum_item_cat_sales_back_2',
 'sum_item_cat_shop_sales_back_2',
 'sum_item_sales_back_3',
 'sum_shop_sales_back_3',
 'item_cnt_month_back_3',
 'sum_item_cat_sales_back_3',
 'sum_item_cat_shop_sales_back_3',
 'sum_item_sales_back_4',
 'sum_shop_sales_back_4',
 'item_cnt_month_back_4',
 'sum_item_cat_sales_back_4',
 'sum_item_cat_shop_sales_back_4',
 'sum_item_sales_back_5',
 'sum_shop_sales_back_5',
 'item_cnt_month_back_5',
 'sum_item_cat_sales_back_5',
 'sum_item_cat_shop_sales_back_5',
 'sum_item_sales_back_6',
 'sum_shop_sales_back_6',
 'item_cnt_month_back_6',
 'sum_item_cat_sales_back_6',
# 'sum_item_cat_shop_sales_back_6',
 'sum_item_sales_back_7',
 'sum_shop_sales_back_7',
 'item_cnt_month_back_7',
 'sum_item_cat_sales_back_7',
# 'sum_item_cat_shop_sales_back_7',
 'sum_item_sales_back_8',
 'sum_shop_sales_back_8',
 'item_cnt_month_back_8',
 'sum_item_cat_sales_back_8',
# 'sum_item_cat_shop_sales_back_8',
 'sum_item_sales_back_9',
 'sum_shop_sales_back_9',
 'item_cnt_month_back_9',
 'sum_item_cat_sales_back_9',
# 'sum_item_cat_shop_sales_back_9',
 'sum_item_sales_back_10',
 'sum_shop_sales_back_10',
 'item_cnt_month_back_10',
 'sum_item_cat_sales_back_10',
# 'sum_item_cat_shop_sales_back_10',
 'sum_item_sales_back_11',
 'sum_shop_sales_back_11',
 'item_cnt_month_back_11',
 'sum_item_cat_sales_back_11',
# 'sum_item_cat_shop_sales_back_11',
 'sum_item_sales_back_12',
 'sum_shop_sales_back_12',
 'item_cnt_month_back_12',
 'sum_item_cat_sales_back_12',
# 'sum_item_cat_shop_sales_back_12',
 'numdays',
 'mean_prevmonth_item_price',
 'std_prevmonth_item_price',
 'median_prevmonth_item_price',
 'median_prevmonth_shop_item_price',
 'prop_median_item_price',
 'first_sale_date_block',
 'new_item']
    
    x_train = [d[FEATS] for d in x_train]
    x_test =  [d[FEATS] for d in x_test]
    return [x_train,x_test,y_train,y_test]

In [28]:
x_train , x_test , y_train , y_test = feat_selection(x_train,x_test,y_train,y_test)

In [29]:
x_train[0].shape

(9934775, 24)

In [30]:
x_test[0].shape

(214200, 24)

In [31]:
y_train[0].shape

(9934775,)

# Reduce Dataset size

In [32]:
#x_train_small = [d.sample(frac=1,random_state=0) for d in x_train]
#y_train_small = [d.sample(frac=1,random_state=0) for d in y_train]
#x_test_small = [d.sample(frac=1,random_state=0) for d in x_test]
#y_test_small = [d.sample(frac=1,random_state=0) for d in y_test]

# Fitting

In [33]:
model = xgb.XGBRegressor(
    seed=0,
    max_depth=3,
    learning_rate=0.5,
    n_estimators=1000,
    objective='reg:linear',
    nthread=8,
    min_child_weight=100,
    colsample_bytree=1,
    subsample=1
)
eval_set = [(x_train[0],y_train[0]),(x_test[0],y_test[0])]

In [ ]:
model.fit(
    verbose=True,
    X=x_train[0],
    y=y_train[0],
    eval_set=eval_set,
    early_stopping_rounds=20
)

[09:00:33] Tree method is automatically selected to be 'approx' for faster speed. to use old behavior(exact greedy algorithm on single machine), set tree_method to 'exact'
[0]	validation_0-rmse:1.0589	validation_1-rmse:0.967299
Multiple eval metrics have been passed: 'validation_1-rmse' will be used for early stopping.

Will train until validation_1-rmse hasn't improved in 20 rounds.
[1]	validation_0-rmse:1.00161	validation_1-rmse:0.923365
[2]	validation_0-rmse:0.981192	validation_1-rmse:0.91065
[3]	validation_0-rmse:0.972664	validation_1-rmse:0.899466
[4]	validation_0-rmse:0.968485	validation_1-rmse:0.900053
[5]	validation_0-rmse:0.965745	validation_1-rmse:0.89813
[6]	validation_0-rmse:0.964154	validation_1-rmse:0.897718

In [ ]:
#np.sqrt(np.mean((model.predict(x_test[0]) - y_test[0])**2))

In [ ]:
ax = xgb.plot_importance(model,height=0.8,)
ax.figure.set_size_inches(5,10)

# EDA

In [ ]:
#item_cat = x_train[0].item_id_encoded_alpha_0
#shop_cat = x_train[0].shop_id_encoded_alpha_0
#y = y_train[0]

In [ ]:
#d = x_train[0]
#d['target'] = y_train[0]
#print(d.plot(x='item_id_encoded_alpha_0',y='target',kind='scatter'))

# Retrain model with all data

# Write Submission

In [ ]:
#SUB=True

In [ ]:
#retrain on all data
#
#
#
#
#
if SUB:
    preds = model.predict(x_test[1])

In [ ]:
if SUB:
    preds

In [ ]:
if SUB:
    #sample_sub = pd.read_csv('../original_data/sample_submission.csv.gz')
    test0 = pd.read_csv('../original_data/test.csv.gz')

In [ ]:
if SUB:
    submission = x_test_1_saved.copy()
    submission['item_cnt_month'] = preds
    submission = test0.merge(submission).drop(['shop_id','item_id'],axis=1)

In [ ]:
if SUB:
    submission.to_csv('../gen_data/model3_basic_sub.csv',index=False)
    submission.head()

In [ ]:
if SUB:
    submission_adjusted = submission
    submission_adjusted['item_cnt_month'] = 0.2839853/submission_adjusted['item_cnt_month'].mean()*submission_adjusted['item_cnt_month']
    submission.to_csv('../gen_data/model3_basic_sub_adjusted.csv',index=False)
    submission_adjusted.head()