In [2]:
import pandas as pd
import numpy as np
import pickle

In [4]:
df = pd.read_csv('../gen_data/train2.csv')

y_train_list = pickle.load(open('../gen_data/y_train--features1.ipynb--.pickle','rb'))
x_train_list = pickle.load(open('../gen_data/x_train--features3.ipynb--.pickle','rb'))
x_test_list = pickle.load(open('../gen_data/x_test--features3.ipynb--.pickle','rb'))

In [13]:
def target_encode(x_train,y_train,x_test,cols,fillna=0):
    x_train['target'] = y_train

#for test data
    for col in cols:
        agged_sum = x_train.groupby(col).target.sum()
        x_test[col+'_encoded'] = x_test[col].map(agged_sum)
        if fillna=='mean':
            x_test[col+'_encoded'].fillna(x_test[col+'_encoded'].mean(),inplace=True)
        elif fillna=='median':
            
            x_test[col+'_encoded'].fillna(x_test[col+'_encoded'].median(),inplace=True)
        else:
            x_test[col+'_encoded'].fillna(fillna,inplace=True)
            
#for train data, need to regularise
    for col in cols:
        
        #
        #
        #
        #
        #
        if fillna=='mean':
            x_test[col+'_encoded'].fillna(x_test[col+'_encoded'].mean(),inplace=True)
        elif fillna=='median':
            
            x_test[col+'_encoded'].fillna(x_test[col+'_encoded'].median(),inplace=True)
        else:
            x_test[col+'_encoded'].fillna(fillna,inplace=True)

    return x_train.drop('target',axis=1) , x_test

In [14]:
x_train = x_train_list[0]
y_train = y_train_list[0]
x_test = x_test_list[0]

In [32]:
x_train_small = x_train[x_train.item_id.isin([31,32])]
x_train_small[['item_id','target']]

         item_id  target
0             32     1.0
896           31     0.0
7551          32     0.0
8447          31     0.0
15102         32     0.0
15998         31     1.0
22653         32     3.0
23549         31     1.0
30204         32     2.0
31100         31     1.0
37755         32     3.0
38651         31     0.0
45306         32     1.0
46202         31     0.0
52857         32     0.0
53753         31     0.0
60408         32     1.0
61304         31     0.0
67959         32     0.0
68855         31     0.0
75510         32     2.0
76406         31     0.0
83061         32     2.0
83957         31     1.0
90612         32     2.0
91508         31     0.0
98163         32     0.0
99059         31     0.0
105714        32     2.0
106610        31     0.0
...          ...     ...
6111856       31     0.0
6111857       32     0.0
6116941       31     0.0
6116942       32     0.0
6122026       31     0.0
6122027       32     1.0
6127111       31     0.0
6127112       32     0.0
6132196       31     1.0
6132197       32     0.0
6137281       31     0.0
6137282       32     0.0
6142366       31     0.0
6142367       32     1.0
6147451       31     0.0
6147452       32     0.0
6152536       31     0.0
6152537       32     2.0
6157621       31     0.0
6157622       32     1.0
6162706       31     0.0
6162707       32     0.0
6167791       31     0.0
6167792       32     0.0
6172876       31     0.0
6172877       32     0.0
6177961       31     0.0
6177962       32     1.0
6183046       31     0.0
6183047       32     0.0

[1990 rows x 2 columns]

In [40]:
cumsum = x_train_small.groupby('item_id').target.cumsum() - x_train_small.target
cumcount = x_train_small.groupby('item_id').target.cumcount()
encoding = cumsum/cumcount

x_train_small['cumsum'] = cumsum
x_train_small['cumcount'] = cumcount
x_train_small['item_id_encoding'] = encoding
x_train_small[['item_id','target','cumsum','cumcount','item_id_encoding']]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

         item_id  target  cumsum  cumcount  item_id_encoding
0             32     1.0     0.0         0               NaN
896           31     0.0     0.0         0               NaN
7551          32     0.0     1.0         1          1.000000
8447          31     0.0     0.0         1          0.000000
15102         32     0.0     1.0         2          0.500000
15998         31     1.0     0.0         2          0.000000
22653         32     3.0     1.0         3          0.333333
23549         31     1.0     1.0         3          0.333333
30204         32     2.0     4.0         4          1.000000
31100         31     1.0     2.0         4          0.500000
37755         32     3.0     6.0         5          1.200000
38651         31     0.0     3.0         5          0.600000
45306         32     1.0     9.0         6          1.500000
46202         31     0.0     3.0         6          0.500000
52857         32     0.0    10.0         7          1.428571
53753         31     0.0     3.0         7          0.428571
60408         32     1.0    10.0         8          1.250000
61304         31     0.0     3.0         8          0.375000
67959         32     0.0    11.0         9          1.222222
68855         31     0.0     3.0         9          0.333333
75510         32     2.0    11.0        10          1.100000
76406         31     0.0     3.0        10          0.300000
83061         32     2.0    13.0        11          1.181818
83957         31     1.0     3.0        11          0.272727
90612         32     2.0    15.0        12          1.250000
91508         31     0.0     4.0        12          0.333333
98163         32     0.0    17.0        13          1.307692
99059         31     0.0     4.0        13          0.307692
105714        32     2.0    17.0        14          1.214286
106610        31     0.0     4.0        14          0.285714
...          ...     ...     ...       ...               ...
6111856       31     0.0   323.0       980          0.329592
6111857       32     0.0   691.0       980          0.705102
6116941       31     0.0   323.0       981          0.329256
6116942       32     0.0   691.0       981          0.704383
6122026       31     0.0   323.0       982          0.328921
6122027       32     1.0   691.0       982          0.703666
6127111       31     0.0   323.0       983          0.328586
6127112       32     0.0   692.0       983          0.703967
6132196       31     1.0   323.0       984          0.328252
6132197       32     0.0   692.0       984          0.703252
6137281       31     0.0   324.0       985          0.328934
6137282       32     0.0   692.0       985          0.702538
6142366       31     0.0   324.0       986          0.328600
6142367       32     1.0   692.0       986          0.701826
6147451       31     0.0   324.0       987          0.328267
6147452       32     0.0   693.0       987          0.702128
6152536       31     0.0   324.0       988          0.327935
6152537       32     2.0   693.0       988          0.701417
6157621       31     0.0   324.0       989          0.327604
6157622       32     1.0   695.0       989          0.702730
6162706       31     0.0   324.0       990          0.327273
6162707       32     0.0   696.0       990          0.703030
6167791       31     0.0   324.0       991          0.326942
6167792       32     0.0   696.0       991          0.702321
6172876       31     0.0   324.0       992          0.326613
6172877       32     0.0   696.0       992          0.701613
6177961       31     0.0   324.0       993          0.326284
6177962       32     1.0   696.0       993          0.700906
6183046       31     0.0   324.0       994          0.325956
6183047       32     0.0   697.0       994          0.701207

[1990 rows x 5 columns]

In [24]:
x_train.head()

,date_block_num,shop_id,item_id,item_category_id,sum_item_sales_back_1,sum_shop_sales_back_1,item_cnt_month_back_1,sum_item_cat_sales_back_1,sum_item_cat_shop_sales_back_1,sum_item_sales_back_2,...,item_cnt_month_back_12,sum_item_cat_sales_back_12,sum_item_cat_shop_sales_back_12,month,numdays,mean_prevmonth_item_price,sd_prevmonth_item_price,mean_prevmonth_shop_item_price,sd_above_market,target
0,12,2,32,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,jan,31,134.691573,15.602202,NaN,0.000000,1.0
1,12,2,33,37.0,42.0,1255.0,1.0,9906.0,55.0,15.0,...,1.0,5982.0,52.0,jan,31,186.571429,16.449056,199.0,0.755580,1.0
2,12,2,99,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,jan,31,124.167083,25.367019,NaN,0.000000,1.0
3,12,2,482,73.0,88.0,1255.0,1.0,412.0,3.0,85.0,...,1.0,664.0,7.0,jan,31,2866.022727,435.543311,3300.0,0.996404,2.0
4,12,2,485,73.0,111.0,1255.0,1.0,412.0,3.0,0.0,...,0.0,0.0,0.0,jan,31,250.203390,51.145216,300.0,0.973632,1.0

In [19]:
x_train_out , x_test_out = target_encode(x_train,y_train,x_test,['item_id'])
x_test_out.sort_values(['item_id']).head(100)

,date_block_num,shop_id,item_id,item_category_id,sum_item_sales_back_1,sum_shop_sales_back_1,item_cnt_month_back_1,sum_item_cat_sales_back_1,sum_item_cat_shop_sales_back_1,sum_item_sales_back_2,...,item_cnt_month_back_12,sum_item_cat_sales_back_12,sum_item_cat_shop_sales_back_12,month,numdays,mean_prevmonth_item_price,sd_prevmonth_item_price,mean_prevmonth_shop_item_price,sd_above_market,item_id_encoded
130087,33,47,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
33187,33,10,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
22987,33,2,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
160687,33,56,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
28087,33,7,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
17887,33,3,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
7687,33,4,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
38287,33,12,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
114787,33,49,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
181087,33,38,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
109687,33,50,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
165787,33,36,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
43387,33,28,30,40.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
124987,33,52,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
63787,33,22,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
94387,33,14,30,40.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
170887,33,37,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
175987,33,35,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
186187,33,34,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
145387,33,58,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
201487,33,44,30,40.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
135187,33,48,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
150487,33,59,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
206587,33,39,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
89287,33,18,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
140287,33,57,30,40.0,0.0,0.0,0.0,0.0,0.0,6.0,...,1.0,13334.0,1039.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
211687,33,45,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
119887,33,53,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
58687,33,25,30,40.0,3.0,4639.0,1.0,6766.0,627.0,0.0,...,3.0,13334.0,824.0,oct,31,119.000000,17.320508,129.0,0.577350,300.0
99487,33,19,30,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,13334.0,222.0,oct,31,119.000000,17.320508,NaN,0.000000,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189294,33,46,31,37.0,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
46494,33,31,31,37.0,9.0,5217.0,1.0,2961.0,261.0,53.0,...,1.0,5036.0,472.0,oct,31,194.666667,13.000000,199.0,0.333333,324.0
128094,33,47,31,37.0,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
594,33,5,31,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,5036.0,45.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
97494,33,19,31,37.0,9.0,1191.0,1.0,2961.0,53.0,0.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,199.0,0.333333,324.0
107694,33,50,31,37.0,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
179094,33,38,31,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
82194,33,16,31,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
15894,33,3,31,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
138294,33,57,31,37.0,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
153594,33,55,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
36294,33,12,31,37.0,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
148494,33,59,31,37.0,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
209694,33,45,31,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,194.666667,13.000000,NaN,0.000000,324.0
189295,33,46,32,40.0,19.0,1242.0,1.0,6766.0,141.0,30.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
71995,33,21,32,40.0,19.0,1727.0,1.0,6766.0,181.0,0.0,...,1.0,13334.0,316.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
51595,33,26,32,40.0,19.0,1212.0,2.0,6766.0,120.0,30.0,...,1.0,13334.0,279.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
10795,33,6,32,40.0,19.0,1602.0,2.0,6766.0,198.0,0.0,...,4.0,13334.0,296.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
163795,33,36,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
158695,33,56,32,40.0,0.0,0.0,0.0,0.0,0.0,30.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
133195,33,48,32,40.0,0.0,0.0,0.0,0.0,0.0,30.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
173995,33,35,32,40.0,0.0,0.0,0.0,0.0,0.0,30.0,...,1.0,13334.0,176.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
122995,33,52,32,40.0,19.0,1057.0,2.0,6766.0,128.0,0.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
209695,33,45,32,40.0,0.0,0.0,0.0,0.0,0.0,30.0,...,1.0,13334.0,95.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
77095,33,15,32,40.0,19.0,1194.0,1.0,6766.0,98.0,0.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
82195,33,16,32,40.0,19.0,936.0,1.0,6766.0,96.0,30.0,...,1.0,13334.0,205.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0
31195,33,10,32,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
41395,33,28,32,40.0,0.0,0.0,0.0,0.0,0.0,30.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
128095,33,47,32,40.0,0.0,0.0,0.0,0.0,0.0,30.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,NaN,0.000000,697.0
56695,33,25,32,40.0,19.0,4639.0,2.0,6766.0,627.0,30.0,...,0.0,0.0,0.0,oct,31,149.000000,0.000000,149.0,0.000000,697.0

In [18]:
x_train['target'] = y_train
x_train.groupby('item_id').target.sum()

item_id
0          1.0
1          6.0
2          2.0
3          2.0
4          1.0
5          1.0
6          1.0
7          1.0
8          2.0
9          1.0
10         1.0
11         1.0
13         1.0
14         1.0
15         1.0
16         1.0
17         1.0
18         1.0
20         1.0
21         1.0
22         1.0
23         1.0
24         1.0
25         1.0
26         1.0
27         6.0
28         1.0
29         1.0
30       300.0
31       324.0
         ...
22132      5.0
22133     30.0
22134      1.0
22135     21.0
22136      6.0
22139    188.0
22140    228.0
22141     53.0
22142     10.0
22143    732.0
22144    116.0
22145    306.0
22146     27.0
22147      4.0
22149      2.0
22150     14.0
22152      3.0
22153      9.0
22154     18.0
22155     16.0
22156      1.0
22159     15.0
22160      1.0
22162    645.0
22163     49.0
22164    462.0
22165      1.0
22166    248.0
22167    900.0
22169      1.0
Name: target, Length: 16561, dtype: float32

In [2]:
def target_encode(df,target,cols,fillna=''):
    df['target'] = target
    for col in cols:
        print('Encoding variable: '+col)
        agged_targ = df.groupby(col).target.sum()
        df[col] = df[col].map(agged_targ)
        if fillna=='mean':
            df[col].fillna(df(col).mean(),inplace=True)
        elif fillna=='median':
            df[col].fillna(df(col).median(),inplace=True)
    return df.drop('target',axis=1)