In [2]:
import pandas as pd
import numpy as np
import pickle
import itertools
from scipy import optimize

In [3]:
train2 = pd.read_csv('../gen_data/train2.csv')
test0 = pd.read_csv('../original_data/test.csv.gz')

In [4]:
dateback_gen = range(1,35)
newdf = test0
val_month = 34
#hardcoded above
for dateback in dateback_gen:
    print(dateback,end=', ')
    train2_month = train2[train2.date_block_num==(val_month-dateback)][['shop_id','item_id','item_cnt_month']]
    train2_month.columns = ['shop_id','item_id','item_cnt_month_back_'+str(dateback)]
    newdf = newdf.merge(train2_month,how='left',on=['shop_id','item_id']).fillna(0)
    #train2_month = test0.merge(train2,on=['shop_id','item_id'],how='left').fillna(0)[['date_block_num','shop_id','item_id','item_cnt_month']]
    #print(train2_month.shape)
    #newdf = pd.concat([newdf,train2_month])

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,

# fix the hardcoded part above

# need to run this on unclipped and possibly cleaned data

In [4]:
#y_train_list = [newdf[newdf.date_block_num<33].item_cnt_month,newdf.item_cnt_month]
#y_test_list = [newdf[newdf.date_block_num==33].item_cnt_month,np.full(214200,np.nan)]
#x_train_list = [newdf[newdf.date_block_num<33],newdf]
#x_test_list = [newdf[newdf.date_bock_num==33],newdf[newdf.date_block_num==34]]

In [10]:
#find a factor to set as solution mean
SOL_MEAN = np.mean(newdf.item_cnt_month_back_1)
SOL_MEAN

0.2556489262371615

In [20]:
ALPHA=1

def validation(ALPHA,verbose=True):
    print('alpha='+str(ALPHA))
    SOLUTION_MEAN = 0.2556489262371615
    preds = test0.copy()

    preds['item_cnt_month']=0.0
    dateback_gen=range(1,34)


    for dateback in dateback_gen:
        
        item_cnt = newdf.iloc[:,dateback+3]
        if verbose:
            print('dateback = '+str(dateback),end='   ')
            print('colname = '+str(item_cnt.name))
        item_cnt = item_cnt.transform(lambda x: x*np.exp(-ALPHA*dateback))
        preds['item_cnt_month'] += item_cnt
    preds['item_cnt_month']=SOLUTION_MEAN/np.mean(preds.item_cnt_month) * preds.item_cnt_month

    return np.sqrt( np.mean( (preds.item_cnt_month - newdf.item_cnt_month_back_1)**2 ) )

In [21]:
optimize.minimize_scalar(validation,tol=0.001)
#found 0.3723609580681796

alpha=0.0
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=1.0
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=2.6180339999999998
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=1.0
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=1.6180339748439998
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.618034
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4

dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.381966025156
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.1433238110471276
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.43678603847576547
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.34885106584240305
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.37383102854531064
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6

dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.3727336917699495
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.3723609580681796
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34
alpha=0.3719885971001114
dateback = 1   colname = item_cnt_month_back_2
dateback = 2   colname = item_cnt_month_back_3
dateback = 3   colname = item_cnt_month_back_4
dateback = 4   colname = item_cnt_month_back_5
dateback = 5   colname = item_cnt_month_back_6
dateback = 6   colname = item_cnt_month_back_7
dateback = 7   colname = item_cnt_month_back_8
dateback = 8   colname = item_cnt_month_back_9
dateback = 9   colname = item_cnt_month_back_10
dateback = 10   colname = item_cnt_month_back_11
dateback = 11   colname = item_cnt_month_back_12
dateback = 12   colname = item_cnt_month_back_13
dateback = 13   colname = item_cnt_month_back_14
dateback = 14   colname = item_cnt_month_back_15
dateback = 15   colname = item_cnt_month_back_16
dateback = 16   colname = item_cnt_month_back_17
dateback = 17   colname = item_cnt_month_back_18
dateback = 18   colname = item_cnt_month_back_19
dateback = 19   colname = item_cnt_month_back_20
dateback = 20   colname = item_cnt_month_back_21
dateback = 21   colname = item_cnt_month_back_22
dateback = 22   colname = item_cnt_month_back_23
dateback = 23   colname = item_cnt_month_back_24
dateback = 24   colname = item_cnt_month_back_25
dateback = 25   colname = item_cnt_month_back_26
dateback = 26   colname = item_cnt_month_back_27
dateback = 27   colname = item_cnt_month_back_28
dateback = 28   colname = item_cnt_month_back_29
dateback = 29   colname = item_cnt_month_back_30
dateback = 30   colname = item_cnt_month_back_31
dateback = 31   colname = item_cnt_month_back_32
dateback = 32   colname = item_cnt_month_back_33
dateback = 33   colname = item_cnt_month_back_34

     fun: 0.9296814063656774
    nfev: 14
     nit: 10
 success: True
       x: 0.3723609580681796

In [22]:
ALPHA=1

def retraining(ALPHA,verbose=True):
    print('alpha='+str(ALPHA))
    SOLUTION_MEAN = 0.2839853
    preds = test0.copy()

    preds['item_cnt_month']=0.0
    dateback_gen=range(1,35)


    for dateback in dateback_gen:
        
        item_cnt = newdf.iloc[:,dateback+2]
        if verbose:
            print('dateback = '+str(dateback),end='   ')
            print('colname = '+str(item_cnt.name))
        item_cnt = item_cnt.transform(lambda x: x*np.exp(-ALPHA*dateback))
        preds['item_cnt_month'] += item_cnt
    preds['item_cnt_month']=SOLUTION_MEAN/np.mean(preds.item_cnt_month) * preds.item_cnt_month

    return preds

In [23]:
preds = retraining(0.3723609580681796)

alpha=0.3723609580681796
dateback = 1   colname = item_cnt_month_back_1
dateback = 2   colname = item_cnt_month_back_2
dateback = 3   colname = item_cnt_month_back_3
dateback = 4   colname = item_cnt_month_back_4
dateback = 5   colname = item_cnt_month_back_5
dateback = 6   colname = item_cnt_month_back_6
dateback = 7   colname = item_cnt_month_back_7
dateback = 8   colname = item_cnt_month_back_8
dateback = 9   colname = item_cnt_month_back_9
dateback = 10   colname = item_cnt_month_back_10
dateback = 11   colname = item_cnt_month_back_11
dateback = 12   colname = item_cnt_month_back_12
dateback = 13   colname = item_cnt_month_back_13
dateback = 14   colname = item_cnt_month_back_14
dateback = 15   colname = item_cnt_month_back_15
dateback = 16   colname = item_cnt_month_back_16
dateback = 17   colname = item_cnt_month_back_17
dateback = 18   colname = item_cnt_month_back_18
dateback = 19   colname = item_cnt_month_back_19
dateback = 20   colname = item_cnt_month_back_20
dateback = 21   colname = item_cnt_month_back_21
dateback = 22   colname = item_cnt_month_back_22
dateback = 23   colname = item_cnt_month_back_23
dateback = 24   colname = item_cnt_month_back_24
dateback = 25   colname = item_cnt_month_back_25
dateback = 26   colname = item_cnt_month_back_26
dateback = 27   colname = item_cnt_month_back_27
dateback = 28   colname = item_cnt_month_back_28
dateback = 29   colname = item_cnt_month_back_29
dateback = 30   colname = item_cnt_month_back_30
dateback = 31   colname = item_cnt_month_back_31
dateback = 32   colname = item_cnt_month_back_32
dateback = 33   colname = item_cnt_month_back_33
dateback = 34   colname = item_cnt_month_back_34

In [24]:
preds.head()

   ID  shop_id  item_id  item_cnt_month
0   0        5     5037        1.065808
1   1        5     5320        0.000000
2   2        5     5233        1.603112
3   3        5     5232        0.170712
4   4        5     5268        0.000000

In [25]:
preds.drop(['shop_id','item_id'],axis=1).to_csv('../naive_sub34.csv',index=False)